AllCops:
  TargetRubyVersion: 2.4

Style/BracesAroundHashParameters:
  EnforcedStyle: braces

Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/PerlBackrefs:
  AutoCorrect: false

Style/RedundantReturn:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Max: 100

Metrics/PerceivedComplexity:
  Enabled: false

Naming/VariableName:
  EnforcedStyle: snake_case