sudo: false
language: ruby
rvm:
- 2.4.1
- 2.4.0
- 2.3
- 2.2
- 2.1
- ruby-head

before_install: gem install bundler -v 1.16.1

matrix:
  allow_failures:
  - rvm: 2.3
  - rvm: 2.2
  - rvm: 2.1
  - rvm: ruby-head

deploy:
  provider: rubygems
  api_key: $RUBYGEMS_API_KEY
  gem: canvas_oss-event
  gemspec: canvas_oss-event.gemspec
  on:
    repo: canvas-oss/canvas-event
    branch: master
    rvm: 2.4.1